---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: /src/k8s.io/helm

steps:
- name: build
  pull: default
  image: golang:1.10
  commands:
  - ./.circleci/bootstrap.sh
  - make test-unit
  - make build
  environment:
    PROJECT_NAME: "\"kubernetes-helm\""

- name: publish-github-rc
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/*"
    prerelease: true
  when:
    event:
    - tag
    ref:
    - "refs/tags/*rc*"
    - refs/heads/rancher

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    checksum:
    - sha256
    files:
    - "bin/*"
    api_key:
      from_secret: github_token
  when:
    event:
    - tag
    ref:
      include:
      - refs/heads/rancher
      exclude:
      - refs/heads/rancher
